name: "Create release"

on:
  push:
    branches:
        - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: 3.x
            cache: pip
            cache-dependency-path: scripts
      - name: Install dependencies
        working-directory: scripts
        run: pip install -r requirements.txt
      - name: Process data
        working-directory: scripts
        run: python3 process_lines.py
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: ${{ github.run_number }}
            files: |
                ris-line-colors.csv
                line-colors.csv
